-- AlterTable
ALTER TABLE "Bailleur" ALTER COLUMN "name" DROP DEFAULT,
ALTER COLUMN "houseId" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Visiteur" ALTER COLUMN "name" DROP DEFAULT,
ALTER COLUMN "houseId" DROP DEFAULT;
